services:
  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - network

  server:
    container_name: ${SERVER_CONTAINER_NAME}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${SERVER_USER}
      POSTGRES_PASSWORD: ${SERVER_PASS}
    ports:
      - "${SERVER_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:

volumes:
  data: